# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-ProcessMap
version:      0.01
version_from: lib/Text/ProcessMap.pm
installdirs:  site
requires:
    Carp:                          0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
